org.gradle.caching=true
group=io.ballerina.lib.redis
version=3.5.0-SNAPSHOT
ballerinaLangVersion=2201.12.12
jacocoVersion=0.8.14

checkstylePluginVersion=10.12.1
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=9.6.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0

lettuceCoreVersion=7.7.0.RELEASE
commonsPool2Version=2.11.1

guavaVersion=32.0.0-jre
commonsIoVersion=2.14.0
nettyVersion=4.2.18.Final
reactorCoreVersion=3.6.6
reactiveStreamsVersion=1.0.4
