name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env: 
          BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11 
        - name: 'Create settings.xml'
          run: |
              echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
                      <activeProfiles>
                        <activeProfile>github</activeProfile>
                      </activeProfiles>

                      <profiles>
                        <profile>
                          <id>github</id>
                          <repositories>
                            <repository>
                              <id>central</id>
                              <url>https://repo1.maven.org/maven2</url>
                              <releases><enabled>true</enabled></releases>
                              <snapshots><enabled>true</enabled></snapshots>
                            </repository>
                            <repository>
                              <id>centralWso2</id>
                              <url>https://maven.wso2.org/nexus/content/repositories/wso2-public/</url>
                              <releases><enabled>true</enabled></releases>
                              <snapshots><enabled>true</enabled></snapshots>
                            </repository>
                            <repository>
                              <id>github</id>
                              <name>GitHub ballerina-platform Apache Maven Packages</name>
                              <url>https://maven.pkg.github.com/ballerina-platform/ballerina-lang</url>
                            </repository>
                          </repositories>
                        </profile>
                      </profiles>

                      <servers>
                        <server>
                          <id>github</id>
                          <username>${{ secrets.BALLERINA_BOT_USERNAME }}</username>
                          <password>${{ secrets.BALLERINA_BOT_TOKEN }}</password>
                        </server>
                      </servers>

                      <mirrors>
                        <mirror>
                          <id>insecure-repo</id>
                          <mirrorOf>external:http:*</mirrorOf>
                          <url>http://maven.wso2.org/nexus/content/repositories/releases/</url>
                          <blocked>false</blocked>
                        </mirror>
                        <mirror>
                          <id>insecure-repo2</id>
                          <mirrorOf>external:http:*</mirrorOf>
                          <url>https://maven.wso2.org/nexus/content/repositories/wso2-public/</url>
                          <blocked>false</blocked>
                        </mirror>
                      </mirrors>

                    </settings>' > ~/.m2/settings.xml
        - name: Maven Build
          run: mvn clean install 
        - name: Ballerina Build
          uses: ballerina-platform/ballerina-action@2201.2.3
          with:
            args:
              pack redis
          env:
            JAVA_HOME: /usr/lib/jvm/default-jvm 
            JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true

        - name: Push to Staging
          if: github.event.inputs.bal_central_environment == 'STAGE'
          uses: ballerina-platform/ballerina-action@2201.2.3
          with:
            args: 
              push
          env:
            JAVA_HOME: /usr/lib/jvm/default-jvm
            WORKING_DIR: ./redis
            BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
        
        - name: Push to Dev
          if: github.event.inputs.bal_central_environment == 'DEV'
          uses: ballerina-platform/ballerina-action@2201.2.3
          with:
            args: 
              push
          env:
            JAVA_HOME: /usr/lib/jvm/default-jvm
            WORKING_DIR: ./redis
            BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
